### ISSUE TITLE
Migrate to 12-factor-app configuration

### ISSUE THREAD

**Issue by powellc** [powellc/findhistory_me#8]
This will include setting up a custom settings file that tries to grab as many variables from the local context as possible. Might also hook up honcho as part of this.

**Comment by jqtrde** [comment]
also make sure to implement 12-factor-authentication for extra security

**Comment by powellc** [comment]
Thanks for the tip!

**Comment by powellc** [comment]
Just closed this one by converting the app to use django-configuratiosn, merged branch feature/configurations into develop
